import Head from 'next/head'
import Navigation from '../src/layout/Navigation'
import 'bootstrap/dist/css/bootstrap.min.css';
import 'antd/dist/antd.css';
import 'react-multi-carousel/lib/styles.css';
import "animate.css/animate.min.css";

import Home from '../src/pages/Home'
export default function index() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Navigation />
        <Home />
      </main>
    </>
  )
}
